language: rust

before_install:
    - wget -O - http://ubuntu.hyperdex.org/hyperdex.gpg.key | sudo apt-key add -
    - sudo wget -O /etc/apt/sources.list.d/hyperdex.list http://ubuntu.hyperdex.org/precise.list
    - sudo apt-get -y update
    - sudo apt-get -y install hyperdex libhyperdex-dev libhyperdex-client-dev libhyperdex-admin-dev
    - sudo ldconfig

script:
    - cargo build --verbose
    - export RUST_TEST_TASKS=1
    - mkdir coord && cd coord && hyperdex coordinator -f -l 127.0.0.1 -p 1982 & 
    - mkdir data && cd data && hyperdex daemon -f --listen=127.0.0.1 --listen-port=2012 --coordinator=127.0.0.1 --coordinator-port=1982 --data=. &
    - cargo test
